### ISSUE TITLE
Exercise Review

### ISSUE THREAD

**Issue by gnesher** [RonaBaker/angular-shop#1]
Good job, well-written code, and nice design.
A few comments:
1. For the list of categories, using an Enum is a bonus
2. Category filter logic is a bit confusing, you assume that the default category is all and then check (this.currentCategoryId !== this.defaultCategory) if it's a 'default category' it can change from all and this check wouldn't work. If you want to compare it to all simply use a different variable name.
3. Page names should be an enum, otherwise, you keep copy/pasting strings across the app and can cause bugs

**Comment by RonaBaker** [comment]
Thanks
